package com.firstprog.universityitschool.Utility;

import android.app.Dialog;
import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.ColorDrawable;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;

import com.firstprog.universityitschool.R;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

public class SubjectAddDialog {

    private Context context;
    private Dialog subDialog;
    private TextView itemTitles;
    private EditText Subject;
    Button submit;
    private LoadingDialog loading_Dialog, loading_Dialog2;
    private DatabaseReference databaseReference, newDatabaseReference, pushedPostRef;
    private FirebaseAuth firebaseAuth;

    public SubjectAddDialog(Context context) {
        this.context = context;
    }

    //display editText view when clicking add button
    public void showDialog(String itemTitle) {
        subDialog = new Dialog(context);
        subDialog.setContentView(R.layout.activity_one_item_add_dialog);
        subDialog.getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));
        subDialog.setCanceledOnTouchOutside(true);

        itemTitles = subDialog.findViewById(R.id.itemTitle);
        itemTitles.setText(itemTitle);

        Subject = subDialog.findViewById(R.id.addItem);

        subDialog.create();
        subDialog.show();
    }

    //return button id to subjectFragment
    public Button submit() {
        return submit = subDialog.findViewById(R.id.btnSubmitItem);
    }

    //upload newly added subject to the firebase
    public void uploadToFirebase(String semesterID, String batchNumber, String semesterNumber) {
        //check internet connection
        if (!CheckNetwork.isConnected(context)) {
            CheckNetwork.showNetworkDialog(context);
        } else {

            loading_Dialog = new LoadingDialog(context);
            String getSubject = Subject.getText().toString();

            if (valid(getSubject)) {
                loading_Dialog.showDialog("Please Wait..");

                databaseReference = FirebaseDatabase.getInstance("https://itschool-auth-default-rtdb.firebaseio.com").getReference("batch").child(batchNumber).child("batch_Sem");

                databaseReference.addListenerForSingleValueEvent(new ValueEventListener() {
                    @Override
                    public void onDataChange(@NonNull DataSnapshot snapshot) {
                        for (DataSnapshot ds : snapshot.getChildren()) {
                            String allSemID = ds.child("semID").getValue().toString();

                            if (allSemID.equals(semesterID)) {
                                newDatabaseReference = ds.child("semester_subject").getRef();
                                // Generate a reference to a new location and add some data using push()
                                pushedPostRef = newDatabaseReference.push();
                                // Get the unique ID generated by a push()
                                String postId = pushedPostRef.getKey();

                                newDatabaseReference.child(postId).child("subMainChildID").setValue(postId);
                                newDatabaseReference.child(postId).child("subID").setValue(getSubject);
                                newDatabaseReference.child(postId).child("bID").setValue(batchNumber);
                                newDatabaseReference.child(postId).child("sID").setValue(semesterNumber);

                                Subject.setText(" ");
                                subDialog.dismiss();
                                loading_Dialog.HideDialog();

                                Toast.makeText(context, "Added Successfully", Toast.LENGTH_SHORT).show();

                            }
                        }
                    }

                    @Override
                    public void onCancelled(@NonNull DatabaseError error) {
                        throw error.toException();
                    }
                });
                subDialog.dismiss();
                loading_Dialog.HideDialog();
            }
        }
    }

    //display editText view with subject details when clicking edit button
    public void showDialogWithDetails(String subject, String itemTitle) {
        //check internet connection
        if (!CheckNetwork.isConnected(context)) {
            CheckNetwork.showNetworkDialog(context);
        } else {

            subDialog = new Dialog(context);
            subDialog.setContentView(R.layout.activity_one_item_add_dialog);
            subDialog.getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));
            subDialog.setCanceledOnTouchOutside(true);

            itemTitles = subDialog.findViewById(R.id.itemTitle);
            itemTitles.setText(itemTitle);

            //set batch number in preview
            Subject = subDialog.findViewById(R.id.addItem);
            Subject.setText(subject);

            subDialog.create();
            subDialog.show();
        }
    }

    //update firebase subject data when clicking edit button
    public void updateFirebaseDetails(String getBatchPreNumber, String getSemesterPreNumber, String pVal) {

        //check internet connection
        if (!CheckNetwork.isConnected(context)) {
            CheckNetwork.showNetworkDialog(context);
        } else {

            loading_Dialog2 = new LoadingDialog(context);

            String newSubject = Subject.getText().toString();

            firebaseAuth = FirebaseAuth.getInstance();
            databaseReference = FirebaseDatabase.getInstance("https://itschool-auth-default-rtdb.firebaseio.com").getReference("batch").child(getBatchPreNumber).child("batch_Sem").child(getSemesterPreNumber).child("semester_subject");

            if (valid(newSubject)) {
                loading_Dialog2.showDialog("Please Wait..");

                databaseReference.addListenerForSingleValueEvent(new ValueEventListener() {
                    @Override
                    public void onDataChange(@NonNull DataSnapshot snapshot) {
                        for (DataSnapshot ds : snapshot.getChildren()) {
                            String allPreVAL = ds.child("subMainChildID").getValue().toString();

                            if (allPreVAL.equals(pVal)) {
                                ds.child("subID").getRef().setValue(newSubject).addOnCompleteListener(new OnCompleteListener<Void>() {
                                    @Override
                                    public void onComplete(@NonNull Task<Void> task) {
                                        subDialog.dismiss();
                                        loading_Dialog2.HideDialog();
                                        Toast.makeText(context, "Update Successful", Toast.LENGTH_SHORT).show();
                                    }
                                });
                            }
                        }
                    }

                    @Override
                    public void onCancelled(@NonNull DatabaseError error) {
                        throw error.toException();
                    }
                });
                loading_Dialog2.HideDialog();
            }
        }

    }

    private boolean valid(String subject) {
        if (subject.isEmpty()) {
            Toast.makeText(context, "Subject Cannot be Empty!", Toast.LENGTH_SHORT).show();
            return false;
        }

        return true;
    }
}
